# fly.toml app configuration file generated for coffea on 2024-04-16T12:19:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

app = 'app-name'
primary_region = 'lhr'

[build]

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[env]
PORT = "8080"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
